name: CI with Caching

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Cache pip downloads
      - name: prime-cache-56ae1fc
        id: prime_cache_56ae1fc
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-56ae1
